/*
 * zoope's AI engine: a language model running in this browser (see brainworker.js).
 *
 * The rule engine (engine.js) decides *when* zoope speaks. Everything zoope says
 * is then generated by the model, as the user, in the moment: answers, small
 * talk, reactions, general knowledge. Replies stream: each sentence is spoken as
 * soon as it has been generated, so zoope starts talking almost right away.
 *
 * Honesty rails: facts about the user's own work, plans, schedule and numbers
 * may only come from their notes. When the notes don't cover something the user
 * was asked, the model marks the reply [ASK] (zoope then pings the user), and a
 * sentence that claims something personal with a number or name found nowhere
 * in the notes or the conversation is dropped.
 */
(function (global) {
  'use strict';
  var worker = null, seq = 0, handlers = {}, state = 'off', device = '', model = '', progress = 0, listeners = [];

  function emit() { listeners.forEach(function (fn) { fn({ state: state, device: device, model: model, progress: progress }); }); }

  var retries = 0;
  function retryLater() {
    if (retries >= 5) return;
    retries++;
    var again = function () { window.removeEventListener('online', again); clearTimeout(t); if (state === 'error') { try { worker.terminate(); } catch (e) { /* gone */ } worker = null; load(); } };
    var t = setTimeout(again, 60000 * retries);
    window.addEventListener('online', again);
  }
  function load() {
    if (worker) return;
    try { worker = new Worker(new URL('js/brainworker.js', document.baseURI), { type: 'module' }); } catch (e) { state = 'error'; emit(); return; }
    worker.onmessage = function (e) {
      var m = e.data;
      if (m.id === 0) {
        if (m.kind === 'progress') { progress = m.total ? m.loaded / m.total : 0; emit(); }
        else if (m.kind === 'ready') { state = 'ready'; device = m.device; model = m.model || ''; emit(); }
        else if (m.kind === 'error') { state = 'error'; emit(); retryLater(); }
        return;
      }
      if (handlers[m.id]) handlers[m.id](m);
    };
    state = 'loading'; emit();
    worker.postMessage({ id: 0, kind: 'load' });
  }

  function words(s) { return String(s).match(/[A-Za-z0-9][\w'%.-]*/g) || []; }
  // a personal claim ("I", "we", "my", "our"…) may only use numbers and names zoope was given
  function grounded(sentence, known) {
    if (!/\b(i|i'm|i'll|i've|we|we're|we'll|my|our|me|us)\b/i.test(sentence)) return true;
    return words(sentence).every(function (w, i, all) {
      var isNum = /\d/.test(w);
      var prev = i > 0 ? all[i - 1] : '';
      var isName = /^[A-Z][a-z]/.test(w) && i > 0 && !/[.!?]$/.test(prev) && !/^I('|$)/.test(w) && !/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|January|February|March|April|May|June|July|August|September|October|November|December)$/.test(w);
      if (!isNum && !isName) return true;
      return known.indexOf(w.toLowerCase().replace(/[.,!?]+$/, '')) >= 0;
    });
  }

  /*
   * Generates a reply and calls onSentence(text) for each sentence as soon as it's ready.
   * opts: { name, fullName, speaker, text, notes: [string], history: [{speaker, text, ai}], firstTimeout }
   * Resolves to { said: [sentences], ask: bool } or null when the model isn't ready / was too slow to start.
   */
  function generate(opts, onSentence) {
    if (state !== 'ready') return Promise.resolve(null);
    var name = opts.name, notes = opts.notes || [];
    var now = new Date();
    var sys = 'You are ' + (opts.fullName || name) + ' (people call you ' + name + '), in a live video meeting. ' +
      'Talk exactly like a real person on a call: first person, natural, warm, conversational, and brief (usually one or two short sentences). ' +
      'You are smart: answer general questions, do math, explain things and make small talk using your own knowledge. ' +
      'It is ' + now.toLocaleString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' }) + '.\n' +
      'Your notes (the only source for facts about your own work, projects, plans, schedule, numbers and decisions):\n' +
      (notes.length ? notes.map(function (n) { return '- ' + n; }).join('\n') : '- (none)') + '\n' +
      'If you are asked about your own work, plans or schedule and your notes do not cover it, do not guess: say naturally that you will check and get back to them, and start your reply with [ASK]. ' +
      'Never make promises or decisions on your own. If someone sincerely asks whether you are an AI or a bot, say honestly that you are ' + name + '\'s AI avatar speaking from their notes.';
    var convo = (opts.history || []).slice(-10).map(function (h) { return (h.ai ? 'You' : h.speaker) + ': ' + h.text; }).join('\n');
    var user = (convo ? 'Conversation so far:\n' + convo + '\n\n' : '') + opts.speaker + ': ' + opts.text + '\n\nReply as ' + name + ', speaking out loud.';
    var known = ' ' + notes.concat((opts.history || []).map(function (h) { return h.speaker + ' ' + h.text; }), [name, opts.fullName || '', opts.speaker, opts.text]).join(' ').toLowerCase() + ' ';

    return new Promise(function (resolve) {
      var id = ++seq, buf = '', said = [], ask = false, finished = false, firstTimer;
      var finish = function (val) {
        if (finished) return;
        finished = true; clearTimeout(firstTimer); delete handlers[id];
        resolve(val);
      };
      var stop = function () { worker.postMessage({ id: id, kind: 'stop' }); };
      var take = function (sentence) {
        var t = sentence.replace(/^\s*["“]|["”]\s*$/g, '').replace(/^(You|Me|[A-Z][a-z]+):\s*/, '').trim();
        if (/\[ASK\]/i.test(t)) { ask = true; t = t.replace(/\[ASK\]\s*/ig, ''); }
        if (!t || !/[a-z]/i.test(t)) return true;
        if (!grounded(t, known)) { stop(); return false; } // drop an ungrounded claim and stop there
        said.push(t);
        clearTimeout(firstTimer);
        onSentence(t);
        if (said.length >= 3) { stop(); return false; } // keep turns short, like people do
        return true;
      };
      handlers[id] = function (m) {
        if (finished) return;
        if (m.kind === 'token') {
          buf += m.text;
          var re = /^([\s\S]*?[.!?])(\s+|$)(?=\s*\S)/, match;
          while ((match = buf.match(re)) && match[1].split(/\s+/).length >= 2) {
            buf = buf.slice(match[0].length);
            if (!take(match[1])) { finish({ said: said, ask: ask }); return; }
          }
        } else if (m.kind === 'done' || m.kind === 'error') {
          if (m.kind === 'done' && buf.trim()) take(buf);
          finish(said.length || ask ? { said: said, ask: ask } : null);
        }
      };
      // a reply that hasn't started speaking within the limit is replaced by the rule engine's
      firstTimer = setTimeout(function () { if (!said.length) { stop(); finish(null); } }, opts.firstTimeout || 2500);
      worker.postMessage({ id: id, kind: 'ask', messages: [{ role: 'system', content: sys }, { role: 'user', content: user }], maxTokens: 90 });
    });
  }

  global.ZoopeBrain = {
    load: load, generate: generate,
    ready: function () { return state === 'ready'; },
    status: function () { return { state: state, device: device, model: model, progress: progress }; },
    onStatus: function (fn) { listeners.push(fn); fn({ state: state, device: device, model: model, progress: progress }); }
  };
})(window);
