/*
 * zoope's AI engine: a language model running in this browser (see brainworker.js).
 *
 * The rule engine (engine.js) decides *when* zoope speaks. Everything zoope says
 * is then generated by the model, as the user, in the moment: answers, small
 * talk, reactions, general knowledge. Replies stream: each sentence is spoken as
 * soon as it has been generated, so zoope starts talking almost right away.
 *
 * Honesty rails: facts about the user's own work, plans, schedule and numbers
 * may only come from their notes. When the notes don't cover something the user
 * was asked, the model marks the reply [ASK] (zoope then pings the user), and a
 * sentence that claims something personal with a number or name found nowhere
 * in the notes or the conversation is dropped.
 */
(function (global) {
  'use strict';
  var lastError = '', worker = null, seq = 0, handlers = {}, state = 'off', device = '', model = '', progress = 0, listeners = [];
  // where the engine runs: 'local' (a worker in this page) or 'ext' (installed in the zoope extension)
  var mode = 'local', source = 'this page';
  function send(msg) {
    if (mode === 'ext') {
      if (msg.kind === 'ask') global.ZoopeBridge.ai.ask(msg.id, msg.messages, msg.maxTokens);
      else if (msg.kind === 'stop') global.ZoopeBridge.ai.stop(msg.id);
    } else if (worker) worker.postMessage(msg);
  }
  function onEngine(m) { if (handlers[m.id]) handlers[m.id](m); }

  /* Use the AI engine installed in the extension (it was connected with the popup's Connect button). */
  function useExtension(st) {
    if (worker) { try { worker.terminate(); } catch (e) { /* gone */ } worker = null; }
    mode = 'ext'; source = 'the zoope extension';
    state = st.state === 'ready' ? 'ready' : st.state === 'error' ? 'error' : 'loading';
    device = st.device || ''; model = st.model || ''; progress = st.progress || 0; lastError = st.error || '';
    emit();
  }
  function watchExtension() {
    var B = global.ZoopeBridge;
    if (!B || !B.ai) return;
    B.ai.on(function (ev) {
      if (ev.type === 'aiStatus' && ev.connected) useExtension(ev);
      else if (ev.type === 'aiEngine' && mode === 'ext') onEngine(ev.msg);
    });
    B.onAvailable(function () {
      B.ai.status().then(function (st) { if (st && st.connected) useExtension(st); });
    });
  }

  function emit() { listeners.forEach(function (fn) { fn({ state: state, device: device, model: model, progress: progress, error: lastError, source: source }); }); }

  var retries = 0;
  function retryLater() {
    if (retries >= 5) return;
    retries++;
    var again = function () { window.removeEventListener('online', again); clearTimeout(t); if (state === 'error' && mode === 'local') { try { worker.terminate(); } catch (e) { /* gone */ } worker = null; load(); } };
    var t = setTimeout(again, 60000 * retries);
    window.addEventListener('online', again);
  }
  function load() {
    if (worker || mode === 'ext') return;
    // if the extension has the AI engine installed, use that instead of loading another copy here
    var B = global.ZoopeBridge;
    if (B && B.available() && !load.checked) {
      load.checked = true;
      B.ai.status().then(function (st) { if (st && st.connected) useExtension(st); else load(); });
      return;
    }
    try { worker = new Worker(new URL('js/brainworker.js', document.baseURI), { type: 'module' }); } catch (e) { state = 'error'; emit(); return; }
    worker.onmessage = function (e) {
      var m = e.data;
      if (m.id === 0) {
        if (m.kind === 'progress') { progress = m.total ? m.loaded / m.total : 0; emit(); }
        else if (m.kind === 'ready') { state = 'ready'; device = m.device; model = m.model || ''; emit(); }
        else if (m.kind === 'error') { state = 'error'; lastError = m.message; if (window.console) console.warn('[zoope AI]', m.message); emit(); retryLater(); }
        return;
      }
      onEngine(m);
    };
    state = 'loading'; emit();
    worker.postMessage({ id: 0, kind: 'load' });
  }

  function sentenceEnd(b) {
    var re = /[.!?](?=\s|$)/g, m;
    while ((m = re.exec(b))) if (b.slice(0, m.index + 1).trim().split(/\s+/).length >= 2) return m.index;
    return -1;
  }
  function words(s) { return String(s).match(/[A-Za-z0-9][\w'%.-]*/g) || []; }
  // a personal claim ("I", "we", "my", "our"…) may only use numbers and names zoope was given
  function grounded(sentence, known) {
    if (!/\b(i|i'm|i'll|i've|we|we're|we'll|my|our|me|us)\b/i.test(sentence)) return true;
    return words(sentence).every(function (w, i, all) {
      var isNum = /\d/.test(w);
      var prev = i > 0 ? all[i - 1] : '';
      var isName = /^[A-Z][a-z]/.test(w) && i > 0 && !/[.!?]$/.test(prev) && !/^I('|$)/.test(w) && !/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|January|February|March|April|May|June|July|August|September|October|November|December)$/.test(w);
      if (!isNum && !isName) return true;
      return known.indexOf(w.toLowerCase().replace(/[.,!?]+$/, '')) >= 0;
    });
  }

  var STYLES = {
    friendly: 'friendly and warm, relaxed, uses first names',
    professional: 'professional and polished, clear and courteous',
    concise: 'concise and direct, gets to the point, no small talk',
    casual: 'casual and upbeat, light humour when it fits',
    thoughtful: 'thoughtful and measured, considers things before answering'
  };
  function similar(a, b) {
    var A = words(a.toLowerCase()), B = {}, hit = 0;
    words(b.toLowerCase()).forEach(function (w) { B[w] = true; });
    A.forEach(function (w) { if (B[w]) hit++; });
    return A.length >= 3 && hit / A.length >= 0.8;
  }

  /*
   * Generates what zoope says and calls onSentence(text) for each sentence as soon as it's ready.
   * opts: { task: 'reply' | 'summon' | 'join' | 'relay', name, fullName, speaker, text, notes: [string],
   *         history: [{speaker, text, ai}], style, instructions, shares: [string], oneOnOne, firstTimeout }
   * Resolves to { said: [sentences], ask: bool } or null when the model isn't ready / produced nothing.
   */
  function generate(opts, onSentence) {
    if (state !== 'ready') return Promise.resolve(null);
    var name = opts.name, task = opts.task || 'reply', full = opts.fullName || name;
    // the notes that relate to what was said first (a shorter prompt starts replying sooner)
    var qw = (String(opts.text || '').toLowerCase().match(/[a-z0-9]{3,}/g) || []);
    var notes = (opts.notes || []).map(function (n) {
      var nw = String(n).toLowerCase(), hit = 0;
      qw.forEach(function (w) { if (nw.indexOf(w) >= 0) hit++; });
      return { n: n, hit: hit };
    }).sort(function (a, b) { return b.hit - a.hit; }).slice(0, 5).map(function (x) { return x.n; });
    var history = (opts.history || []).slice(-14);
    var mine = history.filter(function (h) { return h.ai; }).map(function (h) { return h.text; });
    var now = new Date();
    var sys = 'You are ' + full + (full !== name ? ' (people call you ' + name + ')' : '') + ', speaking out loud on a live video call, in the first person, as yourself.\n' +
      'Personality and style: ' + (STYLES[opts.style] || STYLES.friendly) + '.' + (opts.instructions ? ' Your own instructions: ' + opts.instructions : '') + '\n' +
      'How you talk: like a real person in a meeting. React to what was actually said, specifically. Usually one to three short sentences. ' +
      'No filler or stock phrases ("Great question", "Got it", "Absolutely"), no repeating what you have already said, and vary your wording. ' +
      'Remember the conversation and build on it. If something is unclear or you need more detail before you can answer well, ask one short question instead of answering. ' +
      'Answer general questions, maths and small talk from your own knowledge.\n' +
      'It is ' + now.toLocaleString(undefined, { weekday: 'long', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit' }) + '.\n' +
      'Your notes (the only source for facts about your own work, projects, plans, schedule, numbers and decisions):\n' +
      (notes.length ? notes.map(function (n) { return '- ' + n; }).join('\n') : '- (none)') + '\n' +
      ((opts.shares || []).length ? 'Things you want to bring up in this meeting when it fits naturally:\n' + opts.shares.map(function (n) { return '- ' + n; }).join('\n') + '\n' : '') +
      'If you are asked about your own work or plans and the notes do not cover it, start your reply with [ASK] and say you will check and get back to them. ' +
      'Make no promises or commitments. If someone sincerely asks whether you are an AI, say honestly that you are ' + name + '\'s AI avatar.';
    var convo = history.map(function (h) { return (h.ai ? 'You' : h.speaker) + ': ' + h.text; }).join('\n');
    var said = mine.slice(-5);
    var askLine = task === 'summon' ? opts.speaker + ' just said your name to get your attention and has not said anything else yet. Respond out loud with a very short acknowledgement that invites them to go on.'
      : task === 'join' ? 'You have just joined the call. Greet everyone in one short, natural sentence.'
      : task === 'relay' ? 'You just received this note from yourself to say now: "' + opts.text + '". Say it to the meeting in your own natural words, keeping every fact exactly as written.'
      : opts.speaker + ' just said: "' + opts.text + '"' + (opts.oneOnOne ? ' (it is just the two of you on this call)' : '') + '\nReply to ' + opts.speaker + ' out loud.';
    var user = (convo ? 'The conversation so far:\n' + convo + '\n\n' : '') + (said.length ? 'Lines you have already said (don\'t reuse their wording):\n' + said.map(function (x) { return '- ' + x; }).join('\n') + '\n\n' : '') + askLine;
    var known = ' ' + notes.concat(opts.shares || [], history.map(function (h) { return h.speaker + ' ' + h.text; }), [name, full, opts.speaker || '', opts.text || '']).join(' ').toLowerCase() + ' ';
    var maxSentences = task === 'reply' || task === 'relay' ? 3 : 1;

    return new Promise(function (resolve) {
      var id = ++seq, buf = '', spoken = [], ask = false, finished = false, firstTimer, gotToken = false;
      var finish = function (val) {
        if (finished) return;
        finished = true; clearTimeout(firstTimer); delete handlers[id];
        resolve(val);
      };
      var stop = function () { send({ id: id, kind: 'stop' }); };
      var take = function (sentence) {
        var t = sentence.replace(/^\s*["“]|["”]\s*$/g, '').replace(/^(You|Me|[A-Z][a-z]+):\s*/, '').trim();
        if (/\[ASK\]/i.test(t)) { ask = true; t = t.replace(/\[ASK\]\s*/ig, ''); }
        if (!t || !/[a-z]/i.test(t)) return true;
        if (!grounded(t, known)) { stop(); return false; } // drop an ungrounded claim and stop there
        // never say (nearly) the same sentence twice in a meeting
        if (mine.concat(spoken).some(function (x) { return similar(t, x); })) return true;
        spoken.push(t);
        clearTimeout(firstTimer);
        onSentence(t);
        if (spoken.length >= maxSentences) { stop(); return false; } // keep turns short, like people do
        return true;
      };
      handlers[id] = function (m) {
        if (finished) return;
        if (m.kind === 'token') {
          if (!gotToken) { gotToken = true; clearTimeout(firstTimer); firstTimer = setTimeout(function () { if (!spoken.length && buf.trim()) { take(buf + '.'); buf = ''; } }, 12000); }
          buf += m.text;
          // speak a sentence the moment its closing punctuation arrives (don't wait for the next one);
          // a one-word sentence ("Sure.") is joined with the next
          var end;
          while ((end = sentenceEnd(buf)) >= 0) {
            var sent = buf.slice(0, end + 1);
            buf = buf.slice(end + 1);
            if (!take(sent)) { finish({ said: spoken, ask: ask }); return; }
          }
        } else if (m.kind === 'done' || m.kind === 'error') {
          if (m.kind === 'error') { lastError = m.message; if (window.console) console.warn('[zoope AI]', m.message, m.stack || ''); }
          if (m.kind === 'done' && buf.trim()) take(buf);
          finish(spoken.length || ask ? { said: spoken, ask: ask } : null);
        }
      };
      // if the model produces nothing at all in time, zoope stays quiet rather than say something canned;
      // once it is writing, zoope waits for its sentence
      firstTimer = setTimeout(function () { if (!gotToken) { stop(); finish(null); } }, opts.firstTimeout || 15000);
      send({ id: id, kind: 'ask', messages: [{ role: 'system', content: sys }, { role: 'user', content: user }], maxTokens: task === 'reply' || task === 'relay' ? 110 : 24 });
    });
  }

  watchExtension();

  global.ZoopeBrain = {
    load: load, generate: generate,
    ready: function () { return state === 'ready'; },
    status: function () { return { state: state, device: device, model: model, progress: progress, error: lastError, source: source }; },
    lastError: function () { return lastError; },
    onStatus: function (fn) { listeners.push(fn); fn({ state: state, device: device, model: model, progress: progress }); }
  };
})(window);
